### ISSUE TITLE
-includelast or -specialcases not working

### ISSUE THREAD

**Issue by decstewartje** [arcadesdude/BRU#5]
Nor having any luck getting the -includelast -specialcases switches to work in silent mode. Attempting to use them just hides the application(s) from the selected applications to remove. 

Using Oct.2019 release.

**Comment by arcadesdude** [comment]
decstewartje, could you post or send me the logs (from c:\BRU)? You can use -dr switch for dry run to simulate a run. Also, what's the full command line path and arguments you used to run it and I'll look into it?

**Comment by decstewartje** [comment]
Hi there,

Please find the log attached.
Command called was:
Bloatware-Removal-Utility.ps1 -silent -nd -includelast "HP Client Security Manager","HP Support Assistant" -include "HP\ .*"

I’ve tried the -includelast switch before and after the -include switch with the same result.

Cheers,
Jeremy
[BRU-log.txt](https://github.com/arcadesdude/BRU/files/3794408/BRU-log.txt)

**Comment by arcadesdude** [comment]
I haven't tested it in this specific case but since it is unescaped regular expressions you could try this alternate way of listing programs:

-includelast "HP Client Security Manager|HP Support Assistant"

They're all inside the one "string" separated by | character.

Please note HP Client Security Manager is special as in you need to remove all the hp theft, disk encryption, and a few other pieces first to get it to go away properly. You'll also need the helper application devcon if you run into that weird bug that is in the HP Client Security Manager uninstaller needing the optical drive disabled prior to removal.

Let me know if that works or logs if you can for that test.

Thanks!

**Comment by decstewartje** [comment]
Sorry, i should have mentioned. Also tried using just "HP Client Security Manager" as well as "".*HP\ Client\ Security\ Manager" for -includelast with the same result. Thankfully these were the last HP Client Security Manager installs, do i would never need to run the -includelast switch again. Was just doing some pre-upgrade cleanups.

On a side note... thank you for this awesome tool! Re-imaging is always my first choice, but can't help drop shipping sometimes and this tool is my go-to in those situations.

**Comment by arcadesdude** [comment]
Fixed in https://github.com/arcadesdude/BRU/commit/0adf483c6d5c736a91d1efc877a5c66aa8e7d289
