### ISSUE TITLE
No Bloatware was selected or matched

### ISSUE THREAD

**Issue by beirlaenl** [arcadesdude/BRU#6]
Hi

Let me start with saying this tool has been amazing for me the past few months! Thanks for that.
Now I seem to run into an issue whenever I try to run the silent install where the tool seems to run, it detects installed programs correct but then at the end it finishes with "No Bloatware was selected or matched". The issue is happening on multiple devices and I can't figure out what's going wrong.

EDIT: The command used to run the software is the following (i put this in a separate .bat file):

`powershell.exe -noprofile -executionpolicy bypass -file .\Bloatware-Removal-Utility.ps1 -s -nd -include "HP\ .*","Microsoft Office 365 - nl-nl","Microsoft Office 365 - fr-fr","Microsoft Office 365 - en-us","Microsoft Office 365 - de-de" -exclude "keyboard","driver","HP Universal Camera Driver","HP Hotkey Support","HP Wireless Button Driver" -includelast "HP Client Security Manager","HP Support Assistant" -win10leavestartmenuadson -norestorepoint`

I have attached the log files here:
[Bloatware-Removal-10-jan-2020-10-15.log](https://github.com/arcadesdude/BRU/files/4044874/Bloatware-Removal-10-jan-2020-10-15.log)

**Comment by arcadesdude** [comment]
Glad you find it useful! I'm thinking this may be an issue with quotes (maybe need two " ?) will check and see if I can reproduce/fix.

**Comment by arcadesdude** [comment]
So it's not the quotes. I believe the issue is with the string matching multiple strings.

Can you change your bat file to the below and let me know if that operates as expected. If so I'll change the documentation for the syntax.

powershell.exe -noprofile -executionpolicy bypass -file .\Bloatware-Removal-Utility.ps1 -s -nd -include "HP\ .*|Microsoft Office 365 - nl-nl|Microsoft Office 365 - fr-fr|Microsoft Office 365 - en-us|Microsoft Office 365 - de-de" -exclude "keyboard|driver|HP Universal Camera Driver|HP Hotkey Support|HP Wireless Button Driver" -includelast "HP Client Security Manager|HP Support Assistant" -win10leavestartmenuadson -norestorepoint
